### ISSUE TITLE
lots of erros while executing step "configure && make && make install"

### ISSUE THREAD

**Issue by yogesh9391** [redBorder/f2k#64]
I am trying to install f2k in my ubuntu14 machine by cloning the git repo and executing the the step "./configure && make && make install". However, I'm getting lots of "no such header file errors". Please find below the snippet that I got after executing the step. There were other errors too, which I removed by removing some of dependent packages. But, for below errors, I'm not able to find any proper solution. 

> root@ubuntu:/home/devops/f2k# ./configure
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
checking for librd (by pkg-config)... failed
checking for librd (by compile)... failed (fail)
checking for pcap (by pkg-config)... failed
checking for pcap (by compile)... failed (fail)
checking for librdkafka (by pkg-config)... failed
checking for librdkafka (by compile)... ok
checking for rb_mac_vendor (by pkg-config)... failed
checking for rb_mac_vendor (by compile)... failed (fail)
checking for geoip (by pkg-config)... ok
checking for zookeeper (by pkg-config)... failed
checking for zookeeper (by compile)... ok
checking for udns (by pkg-config)... failed
checking for udns (by compile)... failed (fail)
checking for HAVE_JSON (by pkg-config)... failed
checking for HAVE_JSON (by compile)... ok
checking for optreset (by compile)... failed (disable)
checking for pthread (by pkg-config)... failed
checking for pthread (by compile)... ok
checking for pthread_setaffinity_np (by compile)... failed (disable)
checking for sin6_len (by compile)... failed (disable)
checking for netfilter (by pkg-config)... failed
checking for netfilter (by compile)... failed (disable)
checking for sctp (by compile)... failed (disable)
checking for pcap_next_ex (by compile)... failed (disable)
checking for pf_ring (by pkg-config)... failed
checking for pf_ring (by compile)... failed (disable)
 librd ()
    module: f2k
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lrd -lpthread -lz -lrt
gcc  -Wno-missing-field-initializers -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -O2 -g -Wcast-qual -Wunused -Wextra -Wdisabled-optimization -Wshadow -Wmissing-declarations -Wundef -Wswitch-default -Wmissing-include-dirs -Wstrict-overflow=5 -Winit-self -Wlogical-op -Wcast-align -Wdisabled-optimization -DNDEBUG -D_GNU_SOURCE -DFORTIFY_SOURCE=2 -Wall -Werror -lrd -lpthread -lz -lrt _mkltmp8AkgWk.c -o _mkltmp8AkgWk.c.o  :
_mkltmp8AkgWk.c:1:22: fatal error: librd/rd.h: No such file or directory
 #include <librd/rd.h>
                      ^
compilation terminated.
source: #include <librd/rd.h>
pcap ()
    module: f2k
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpcap
gcc  -Wno-missing-field-initializers -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -O2 -g -Wcast-qual -Wunused -Wextra -Wdisabled-optimization -Wshadow -Wmissing-declarations -Wundef -Wswitch-default -Wmissing-include-dirs -Wstrict-overflow=5 -Winit-self -Wlogical-op -Wcast-align -Wdisabled-optimization -DNDEBUG -D_GNU_SOURCE -DFORTIFY_SOURCE=2 -Wall -Werror -lpcap _mkltmpDRRB09.c -o _mkltmpDRRB09.c.o  :
/usr/bin/ld: cannot find -lpcap
collect2: error: ld returned 1 exit status
source:
 rb_mac_vendor (HAVE_RB_MAC_VENDORS)
    module: f2k
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lrb_mac_vendors
gcc  -Wno-missing-field-initializers -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -O2 -g -Wcast-qual -Wunused -Wextra -Wdisabled-optimization -Wshadow -Wmissing-declarations -Wundef -Wswitch-default -Wmissing-include-dirs -Wstrict-overflow=5 -Winit-self -Wlogical-op -Wcast-align -Wdisabled-optimization -DNDEBUG -D_GNU_SOURCE -DFORTIFY_SOURCE=2 -Wall -Werror -lrb_mac_vendors _mkltmpmtvaLo.c -o _mkltmpmtvaLo.c.o  :
_mkltmpmtvaLo.c:1:28: fatal error: rb_mac_vendors.h: No such file or directory
 #include <rb_mac_vendors.h>
compilation terminated.
source: #include <rb_mac_vendors.h>
udns (HAVE_UDNS)
    module: f2k
    action: fail
    reason:
compile check failed:
CC: CC
flags: -ludns
gcc -I/usr/include/ -Wno-missing-field-initializers -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -O2 -g -Wcast-qual -Wunused -Wextra -Wdisabled-optimization -Wshadow -Wmissing-declarations -Wundef -Wswitch-default -Wmissing-include-dirs -Wstrict-overflow=5 -Winit-self -Wlogical-op -Wcast-align -Wdisabled-optimization -DNDEBUG -D_GNU_SOURCE -DFORTIFY_SOURCE=2 -Wall -Werror -ludns _mkltmpNkVGfP.c -o _mkltmpNkVGfP.c.o  :
/tmp/ccA5w4FZ.o: In function `f':
/home/devops/f2k/_mkltmpNkVGfP.c:2: undefined reference to `dns_init'
collect2: error: ld returned 1 exit status
source: #include <udns.h>
            void *f();void *f(){return dns_init;}

**Comment by malvads** [comment]
Closing, we are currently supporting rhel9, sorry <3
